// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import path from "node:path";
import { defineConfig } from "prisma/config";

process.env.PRISMA_SCHEMA_ENGINE_BINARY ||= path.join(
  process.cwd(),
  "node_modules",
  "@prisma",
  "engines",
  "schema-engine-windows.exe"
);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
